name: pre-commit Update

on:
  schedule:
    - cron: "0 7 1/7 * *" # At 7:00 every 7 days
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit-update:
    runs-on: ubuntu-latest

    # Shouldn't run when the PR comes from a fork
    if: ${{ !github.event.pull_request.head.repo.fork }}

    steps:
      - uses: actions/checkout@v6
      - name: Hack for setup-python cache # https://github.com/actions/setup-python/issues/807
        run: touch requirements.txt
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          cache: pip
          python-version: "3.11"
      - name: Hack for setup-python cache # https://github.com/actions/setup-python/issues/807
        run: rm requirements.txt
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit's autoupdate
        run: |
          # ignore exit code
          pre-commit autoupdate || true
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore: pre-commit update"
          title: "[AUTO] pre-commit update"
          body: "Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action; Please update this PR in some way to trigger workflows"
          branch: auto-pre-commit-update
          reviewers: AntonReinhard
          delete-branch: true
          labels: chore
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
